### ISSUE TITLE
Cannot connect to IBM Cloud MQ

### ISSUE THREAD

**Issue by vedran-kolka-syntio** [ibm-messaging/mq-dev-samples#16]
Following this tutorial ([README](https://github.com/ibm-messaging/mq-dev-samples#using-the-gettingstartedjms-samples-with-tls-ibm-ddc-mq-badge-lab)), I end up with the following exception:
`MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2035' ('MQRC_NOT_AUTHORIZED').`

Difference from the actual tutorial:
- I am using a newer version of the `ibm.mq.allclient` (9.3.2.1) as with the older (9.2.2.2) I had an Exception due to deprecation
- I also added `json-20230227.jar` as a dependency because of a `ClassNotFoundException: org.json.JSONException` 
- I have also set up a keystore for my client (following the steps for creating a self-signed certificate on this [page](https://developer.ibm.com/tutorials/mq-secure-msgs-tls/#step-1-create-tls-objects) and importing the certificate to MQ's keystore through the IBM Cloud Console) because I noticed in the logs that the client would send a "Produced client Certificate message" with an empty list of certificates.

Setting up a client keystore seems to work, because now the handshake looks good, but the example fails with the following stacktrace:
```
> java -Djavax.net.ssl.trustStore=clientTruststore.p12 -Djavax.net.ssl.trustStorePassword=passw0rd -Djavax.net.ssl.keyStore=clientKeystore.p12 -Djavax.net.ssl.keyStorePassword=passw0rd -Djavax.net.debug=ssl,handshake -cp .\com.ibm.mq.allclient-9.2.5.0.jar;.\javax.jms-api-2.0.1.jar;.\json-20230227.jar;. com.ibm.mq.samples.jms.JmsPut

...
javax.net.ssl|DEBUG|10|main|2023-05-11 10:23:30.017 CEST|Finished.java:687|Produced client Finished handshake message (
"Finished": {
  "verify data": {
    ...
  }
}
)
javax.net.ssl|DEBUG|10|main|2023-05-11 10:23:30.018 CEST|SSLCipher.java:2626|algorithm = ChaCha20-Poly1305:KEYUPDATE
countdown value = 0
Exception in thread "main" com.ibm.msg.client.jms.DetailedJMSSecurityRuntimeException: JMSWMQ2007: Failed to send a message to destination 'MY_QUEUE'.
JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
Use the linked exception to determine the cause of this error.
        at com.ibm.msg.client.jms.DetailedJMSSecurityException.getUnchecked(DetailedJMSSecurityException.java:270)
        at com.ibm.msg.client.jms.internal.JmsErrorUtils.convertJMSException(JmsErrorUtils.java:173)
        at com.ibm.msg.client.jms.internal.JmsProducerImpl.send(JmsProducerImpl.java:618)
        at com.ibm.mq.samples.jms.JmsPut.main(JmsPut.java:109)
Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2035' ('MQRC_NOT_AUTHORIZED').
        at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
        at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1358)
        at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1313)
        at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:75)
        at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiUnidentifiedProducerShadow.sendInternal(WMQMessageProducer.java:1123)
        at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:608)
        at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1487)
        at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
        at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
        at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
        at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1535)
        at com.ibm.msg.client.jms.internal.JmsProducerImpl.send(JmsProducerImpl.java:609)
        ... 1 more
```

**Comment by chughts** [comment]
The readme in this repo needs to be updated, as it looks to be out of date. 

A better set of intstructions is [mq-develop-mq-jms-tutorial](https://developer.ibm.com/tutorials/mq-develop-mq-jms/)

You will need to take a look at the queue manager logs to determine the root cause of the `2035`

You may be better off using the samples from the [Patterns](https://github.com/ibm-messaging/mq-dev-patterns) repository.

**Comment by vedran-kolka-syntio** [comment]
The linked tutorial is better, thanks! It confirmed the problem wasn't on the client and the logs on the Queue manager showed that the newly created application user didn't have permissions to put/get to/from the queue.

The readme (and tutorial) could be updated to point this out.
**For anyone else with this problem**: permissions can be set through the MQ Console by selecting the queue -> Actions -> View configuration -> security tab -> Add -> type the username and select required permissions -> Add
